version: '3'
 
services:

  backend:
    image: openjdk:10-jre-slim
    container_name: todo-angular-
    ports:
      - 2604:2604
    volumes:
      - ./todos-springboot-backend/build/libs/todos-springboot-backend-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork
       
  frontend:
    image: nginx:alpine
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./todo-angular-frontend/dist/todo-angular-frontend/:/usr/share/nginx/html
    networks:
      - frontendNetwork
   
networks:
  backendNetwork:
  frontendNetwork: