server.port: 2604
spring.profiles.active: h2

---
spring:
  security:
    user:
      name: john
      password: doe
---

spring:
  profiles: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:todoappdb;MODE=PostgreSQL
    platform: h2
    continue-on-error: false
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      show_sql: true
      use_sql_comments: true
---
