server.port: 2604
spring.profiles.active: prod

---
spring:
  security:
    user:
      name: test
      password: test
---

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:todoappdb;MODE=PostgreSQL
    platform: h2
    continue-on-error: false
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      show_sql: true
      use_sql_comments: true
---


spring:
  profiles: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskapp_db_admin
    password: taskuser123456
  jpa: #spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        show_sql: false
        #schema_update:
         # unique_constraint_strategy: RECREATE_QUIETLY
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

---


logging:
  level:
    root: INFO
    de.webapp.springboot.todos: INFO
